### ISSUE TITLE
Do not require the checkout action to be run as a prerequisite

### ISSUE THREAD

**Issue by noahnu** [tophat/commit-watch-action#5]
**Is your feature request related to a problem? Please describe.**

Currently to use this github action, you need to run:

```yml
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
```

first.

**Describe the solution you'd like**

Detect if a checkout is required, and if it is, use actions/github to perform this checkout.

**Describe alternatives you've considered**

Build this directly into commit-watch.
